name: Release to STG

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN_STG }}
      DATABRICKS_REPO_ID: ${{ secrets.DATABRICKS_REPO_ID_STG }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install Databricks CLI
      run: |
        python -m pip install --upgrade pip
        pip install databricks-cli
    - name: Update repo
      run: databricks repos update --repo-id $DATABRICKS_REPO_ID --branch "main"
