name: Release modeling to STG

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DATABRICKS_BASE_URL_STG: ${{ secrets.DATABRICKS_BASE_URL_STG }}
      DATABRICKS_TOKEN_STG: ${{ secrets.DATABRICKS_TOKEN_STG }}
      DATABRICKS_REPO_ID_STG: ${{ secrets.DATABRICKS_REPO_ID_STG }}

    steps:
    # 1) Checkout
    - uses: actions/checkout@v2

    # 2) Update repo on STG
    - name: Update repo on STG
      run: |
        code=$(curl -w "%{http_code}\n" -o output.txt -n -X PATCH $DATABRICKS_BASE_URL_STG/api/2.0/repos/$DATABRICKS_REPO_ID_STG -H "Authorization: Bearer ${DATABRICKS_TOKEN_STG}" -d '{"branch": "main"}')
        if [[ "code" -ne 200 ]]; then
          echo "Updating of respository failed on STG!"
          cat output.txt
          exit 1
        fi
  
