name: Release to STG

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN_STG }}
      DATABRICKS_REPO_ID_STG: ${{ secrets.DATABRICKS_REPO_ID_STG }}

    steps:
    - uses: actions/checkout@v2
    
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Update repo
      run: databricks repos update --repo-id $DATABRICKS_REPO_ID_STG --tag $RELEASE_VERSION
