name: Release to STG

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN_STG }}
      DATABRICKS_REPO_ID_STG: ${{ secrets.DATABRICKS_REPO_ID_STG }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install Databricks CLI
      run: |
        python -m pip install --upgrade pip
        pip install databricks-cli
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Update repo
      run: databricks repos update --repo-id $DATABRICKS_REPO_ID_STG --tag $RELEASE_VERSION
